//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.11 at 02:26:20 PM EEST 
//


package com.search.tm.utils.parse.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{}data-available-code"/>
 *         &lt;element ref="{}file-segments" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dataAvailableCode",
    "fileSegments"
})
@XmlRootElement(name = "application-information")
public class ApplicationInformation {

    @XmlElement(name = "data-available-code")
    protected String dataAvailableCode;
    @XmlElement(name = "file-segments")
    protected List<FileSegments> fileSegments;

    /**
     * Gets the value of the dataAvailableCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataAvailableCode() {
        return dataAvailableCode;
    }

    /**
     * Sets the value of the dataAvailableCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataAvailableCode(String value) {
        this.dataAvailableCode = value;
    }

    /**
     * Gets the value of the fileSegments property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fileSegments property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFileSegments().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FileSegments }
     * 
     * 
     */
    public List<FileSegments> getFileSegments() {
        if (fileSegments == null) {
            fileSegments = new ArrayList<FileSegments>();
        }
        return this.fileSegments;
    }

}
