//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.11 at 02:26:20 PM EEST 
//


package com.search.tm.utils.parse.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}serial-number"/>
 *         &lt;element ref="{}registration-number" minOccurs="0"/>
 *         &lt;element ref="{}transaction-date" minOccurs="0"/>
 *         &lt;element ref="{}case-file-header" minOccurs="0"/>
 *         &lt;element ref="{}case-file-statements" minOccurs="0"/>
 *         &lt;element ref="{}case-file-event-statements" minOccurs="0"/>
 *         &lt;element ref="{}prior-registration-applications" minOccurs="0"/>
 *         &lt;element ref="{}foreign-applications" minOccurs="0"/>
 *         &lt;element ref="{}classifications" minOccurs="0"/>
 *         &lt;element ref="{}correspondent" minOccurs="0"/>
 *         &lt;element ref="{}case-file-owners" minOccurs="0"/>
 *         &lt;element ref="{}design-searches" minOccurs="0"/>
 *         &lt;element ref="{}international-registration" minOccurs="0"/>
 *         &lt;element ref="{}madrid-international-filing-requests" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "serialNumber",
    "registrationNumber",
    "transactionDate",
    "caseFileHeader",
    "caseFileStatements",
    "caseFileEventStatements",
    "priorRegistrationApplications",
    "foreignApplications",
    "classifications",
    "correspondent",
    "caseFileOwners",
    "designSearches",
    "internationalRegistration",
    "madridInternationalFilingRequests"
})
@XmlRootElement(name = "case-file")
public class CaseFile {

    @XmlElement(name = "serial-number", required = true)
    protected String serialNumber;
    @XmlElement(name = "registration-number")
    protected String registrationNumber;
    @XmlElement(name = "transaction-date")
    protected String transactionDate;
    @XmlElement(name = "case-file-header")
    protected CaseFileHeader caseFileHeader;
    @XmlElement(name = "case-file-statements")
    protected CaseFileStatements caseFileStatements;
    @XmlElement(name = "case-file-event-statements")
    protected CaseFileEventStatements caseFileEventStatements;
    @XmlElement(name = "prior-registration-applications")
    protected PriorRegistrationApplications priorRegistrationApplications;
    @XmlElement(name = "foreign-applications")
    protected ForeignApplications foreignApplications;
    protected Classifications classifications;
    protected Correspondent correspondent;
    @XmlElement(name = "case-file-owners")
    protected CaseFileOwners caseFileOwners;
    @XmlElement(name = "design-searches")
    protected DesignSearches designSearches;
    @XmlElement(name = "international-registration")
    protected InternationalRegistration internationalRegistration;
    @XmlElement(name = "madrid-international-filing-requests")
    protected MadridInternationalFilingRequests madridInternationalFilingRequests;
    
    private List<CaseFileOwner> listOwners = new ArrayList<>(); 
    
    /**
     * Gets the value of the serialNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSerialNumber() {
        return serialNumber;
    }

    /**
     * Sets the value of the serialNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSerialNumber(String value) {
        this.serialNumber = value;
    }

    /**
     * Gets the value of the registrationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegistrationNumber() {
        return registrationNumber;
    }

    /**
     * Sets the value of the registrationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegistrationNumber(String value) {
        this.registrationNumber = value;
    }

    /**
     * Gets the value of the transactionDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionDate() {
        return transactionDate;
    }

    /**
     * Sets the value of the transactionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionDate(String value) {
        this.transactionDate = value;
    }

    /**
     * Gets the value of the caseFileHeader property.
     * 
     * @return
     *     possible object is
     *     {@link CaseFileHeader }
     *     
     */
    public CaseFileHeader getCaseFileHeader() {
        return caseFileHeader;
    }

    /**
     * Sets the value of the caseFileHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link CaseFileHeader }
     *     
     */
    public void setCaseFileHeader(CaseFileHeader value) {
        this.caseFileHeader = value;
    }

    /**
     * Gets the value of the caseFileStatements property.
     * 
     * @return
     *     possible object is
     *     {@link CaseFileStatements }
     *     
     */
    public CaseFileStatements getCaseFileStatements() {
        return caseFileStatements;
    }

    /**
     * Sets the value of the caseFileStatements property.
     * 
     * @param value
     *     allowed object is
     *     {@link CaseFileStatements }
     *     
     */
    public void setCaseFileStatements(CaseFileStatements value) {
        this.caseFileStatements = value;
    }

    /**
     * Gets the value of the caseFileEventStatements property.
     * 
     * @return
     *     possible object is
     *     {@link CaseFileEventStatements }
     *     
     */
    public CaseFileEventStatements getCaseFileEventStatements() {
        return caseFileEventStatements;
    }

    /**
     * Sets the value of the caseFileEventStatements property.
     * 
     * @param value
     *     allowed object is
     *     {@link CaseFileEventStatements }
     *     
     */
    public void setCaseFileEventStatements(CaseFileEventStatements value) {
        this.caseFileEventStatements = value;
    }

    /**
     * Gets the value of the priorRegistrationApplications property.
     * 
     * @return
     *     possible object is
     *     {@link PriorRegistrationApplications }
     *     
     */
    public PriorRegistrationApplications getPriorRegistrationApplications() {
        return priorRegistrationApplications;
    }

    /**
     * Sets the value of the priorRegistrationApplications property.
     * 
     * @param value
     *     allowed object is
     *     {@link PriorRegistrationApplications }
     *     
     */
    public void setPriorRegistrationApplications(PriorRegistrationApplications value) {
        this.priorRegistrationApplications = value;
    }

    /**
     * Gets the value of the foreignApplications property.
     * 
     * @return
     *     possible object is
     *     {@link ForeignApplications }
     *     
     */
    public ForeignApplications getForeignApplications() {
        return foreignApplications;
    }

    /**
     * Sets the value of the foreignApplications property.
     * 
     * @param value
     *     allowed object is
     *     {@link ForeignApplications }
     *     
     */
    public void setForeignApplications(ForeignApplications value) {
        this.foreignApplications = value;
    }

    /**
     * Gets the value of the classifications property.
     * 
     * @return
     *     possible object is
     *     {@link Classifications }
     *     
     */
    public Classifications getClassifications() {
        return classifications;
    }

    /**
     * Sets the value of the classifications property.
     * 
     * @param value
     *     allowed object is
     *     {@link Classifications }
     *     
     */
    public void setClassifications(Classifications value) {
        this.classifications = value;
    }

    /**
     * Gets the value of the correspondent property.
     * 
     * @return
     *     possible object is
     *     {@link Correspondent }
     *     
     */
    public Correspondent getCorrespondent() {
        return correspondent;
    }

    /**
     * Sets the value of the correspondent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Correspondent }
     *     
     */
    public void setCorrespondent(Correspondent value) {
        this.correspondent = value;
    }

    /**
     * Gets the value of the caseFileOwners property.
     * 
     * @return
     *     possible object is
     *     {@link CaseFileOwners }
     *     
     */
    public List<CaseFileOwner> getCaseFileOwners() {
        return this.listOwners;
    }

    /**
     * Sets the value of the caseFileOwners property.
     * 
     * @param value
     *     allowed object is
     *     {@link CaseFileOwners }
     *     
     */
    public void setCaseFileOwners(List<CaseFileOwner> value) {
        this.listOwners = value;
    }

    /**
     * Gets the value of the designSearches property.
     * 
     * @return
     *     possible object is
     *     {@link DesignSearches }
     *     
     */
    public DesignSearches getDesignSearches() {
        return designSearches;
    }

    /**
     * Sets the value of the designSearches property.
     * 
     * @param value
     *     allowed object is
     *     {@link DesignSearches }
     *     
     */
    public void setDesignSearches(DesignSearches value) {
        this.designSearches = value;
    }

    /**
     * Gets the value of the internationalRegistration property.
     * 
     * @return
     *     possible object is
     *     {@link InternationalRegistration }
     *     
     */
    public InternationalRegistration getInternationalRegistration() {
        return internationalRegistration;
    }

    /**
     * Sets the value of the internationalRegistration property.
     * 
     * @param value
     *     allowed object is
     *     {@link InternationalRegistration }
     *     
     */
    public void setInternationalRegistration(InternationalRegistration value) {
        this.internationalRegistration = value;
    }

    /**
     * Gets the value of the madridInternationalFilingRequests property.
     * 
     * @return
     *     possible object is
     *     {@link MadridInternationalFilingRequests }
     *     
     */
    public MadridInternationalFilingRequests getMadridInternationalFilingRequests() {
        return madridInternationalFilingRequests;
    }

    /**
     * Sets the value of the madridInternationalFilingRequests property.
     * 
     * @param value
     *     allowed object is
     *     {@link MadridInternationalFilingRequests }
     *     
     */
    public void setMadridInternationalFilingRequests(MadridInternationalFilingRequests value) {
        this.madridInternationalFilingRequests = value;
    }

}
