//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.11 at 02:26:20 PM EEST 
//


package com.search.tm.utils.parse.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}filing-date" minOccurs="0"/>
 *         &lt;element ref="{}registration-date" minOccurs="0"/>
 *         &lt;element ref="{}status-code" minOccurs="0"/>
 *         &lt;element ref="{}status-date" minOccurs="0"/>
 *         &lt;element ref="{}mark-identification" minOccurs="0"/>
 *         &lt;element ref="{}mark-drawing-code" minOccurs="0"/>
 *         &lt;element ref="{}published-for-opposition-date" minOccurs="0"/>
 *         &lt;element ref="{}amend-to-register-date" minOccurs="0"/>
 *         &lt;element ref="{}abandonment-date" minOccurs="0"/>
 *         &lt;element ref="{}cancellation-code" minOccurs="0"/>
 *         &lt;element ref="{}cancellation-date" minOccurs="0"/>
 *         &lt;element ref="{}republished-12c-date" minOccurs="0"/>
 *         &lt;element ref="{}domestic-representative-name" minOccurs="0"/>
 *         &lt;element ref="{}attorney-docket-number" minOccurs="0"/>
 *         &lt;element ref="{}attorney-name" minOccurs="0"/>
 *         &lt;element ref="{}principal-register-amended-in" minOccurs="0"/>
 *         &lt;element ref="{}supplemental-register-amended-in" minOccurs="0"/>
 *         &lt;element ref="{}trademark-in" minOccurs="0"/>
 *         &lt;element ref="{}collective-trademark-in" minOccurs="0"/>
 *         &lt;element ref="{}service-mark-in" minOccurs="0"/>
 *         &lt;element ref="{}collective-service-mark-in" minOccurs="0"/>
 *         &lt;element ref="{}collective-membership-mark-in" minOccurs="0"/>
 *         &lt;element ref="{}certification-mark-in" minOccurs="0"/>
 *         &lt;element ref="{}cancellation-pending-in" minOccurs="0"/>
 *         &lt;element ref="{}published-concurrent-in" minOccurs="0"/>
 *         &lt;element ref="{}concurrent-use-in" minOccurs="0"/>
 *         &lt;element ref="{}concurrent-use-proceeding-in" minOccurs="0"/>
 *         &lt;element ref="{}interference-pending-in" minOccurs="0"/>
 *         &lt;element ref="{}opposition-pending-in" minOccurs="0"/>
 *         &lt;element ref="{}section-12c-in" minOccurs="0"/>
 *         &lt;element ref="{}section-2f-in" minOccurs="0"/>
 *         &lt;element ref="{}section-2f-in-part-in" minOccurs="0"/>
 *         &lt;element ref="{}renewal-filed-in" minOccurs="0"/>
 *         &lt;element ref="{}section-8-filed-in" minOccurs="0"/>
 *         &lt;element ref="{}section-8-partial-accept-in" minOccurs="0"/>
 *         &lt;element ref="{}section-8-accepted-in" minOccurs="0"/>
 *         &lt;element ref="{}section-15-acknowledged-in" minOccurs="0"/>
 *         &lt;element ref="{}section-15-filed-in" minOccurs="0"/>
 *         &lt;element ref="{}supplemental-register-in" minOccurs="0"/>
 *         &lt;element ref="{}foreign-priority-in" minOccurs="0"/>
 *         &lt;element ref="{}change-registration-in" minOccurs="0"/>
 *         &lt;element ref="{}intent-to-use-in" minOccurs="0"/>
 *         &lt;element ref="{}intent-to-use-current-in" minOccurs="0"/>
 *         &lt;element ref="{}filed-as-use-application-in" minOccurs="0"/>
 *         &lt;element ref="{}amended-to-use-application-in" minOccurs="0"/>
 *         &lt;element ref="{}use-application-currently-in" minOccurs="0"/>
 *         &lt;element ref="{}amended-to-itu-application-in" minOccurs="0"/>
 *         &lt;element ref="{}filing-basis-filed-as-44d-in" minOccurs="0"/>
 *         &lt;element ref="{}amended-to-44d-application-in" minOccurs="0"/>
 *         &lt;element ref="{}filing-basis-current-44d-in" minOccurs="0"/>
 *         &lt;element ref="{}filing-basis-filed-as-44e-in" minOccurs="0"/>
 *         &lt;element ref="{}filing-basis-current-44e-in" minOccurs="0"/>
 *         &lt;element ref="{}amended-to-44e-application-in" minOccurs="0"/>
 *         &lt;element ref="{}without-basis-currently-in" minOccurs="0"/>
 *         &lt;element ref="{}filing-current-no-basis-in" minOccurs="0"/>
 *         &lt;element ref="{}color-drawing-filed-in" minOccurs="0"/>
 *         &lt;element ref="{}color-drawing-current-in" minOccurs="0"/>
 *         &lt;element ref="{}drawing-3d-filed-in" minOccurs="0"/>
 *         &lt;element ref="{}drawing-3d-current-in" minOccurs="0"/>
 *         &lt;element ref="{}standard-characters-claimed-in" minOccurs="0"/>
 *         &lt;element ref="{}filing-basis-filed-as-66a-in" minOccurs="0"/>
 *         &lt;element ref="{}filing-basis-current-66a-in" minOccurs="0"/>
 *         &lt;element ref="{}renewal-date" minOccurs="0"/>
 *         &lt;element ref="{}law-office-assigned-location-code" minOccurs="0"/>
 *         &lt;element ref="{}current-location" minOccurs="0"/>
 *         &lt;element ref="{}location-date" minOccurs="0"/>
 *         &lt;element ref="{}employee-name" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "filingDate",
    "registrationDate",
    "statusCode",
    "statusDate",
    "markIdentification",
    "markDrawingCode",
    "publishedForOppositionDate",
    "amendToRegisterDate",
    "abandonmentDate",
    "cancellationCode",
    "cancellationDate",
    "republished12CDate",
    "domesticRepresentativeName",
    "attorneyDocketNumber",
    "attorneyName",
    "principalRegisterAmendedIn",
    "supplementalRegisterAmendedIn",
    "trademarkIn",
    "collectiveTrademarkIn",
    "serviceMarkIn",
    "collectiveServiceMarkIn",
    "collectiveMembershipMarkIn",
    "certificationMarkIn",
    "cancellationPendingIn",
    "publishedConcurrentIn",
    "concurrentUseIn",
    "concurrentUseProceedingIn",
    "interferencePendingIn",
    "oppositionPendingIn",
    "section12CIn",
    "section2FIn",
    "section2FInPartIn",
    "renewalFiledIn",
    "section8FiledIn",
    "section8PartialAcceptIn",
    "section8AcceptedIn",
    "section15AcknowledgedIn",
    "section15FiledIn",
    "supplementalRegisterIn",
    "foreignPriorityIn",
    "changeRegistrationIn",
    "intentToUseIn",
    "intentToUseCurrentIn",
    "filedAsUseApplicationIn",
    "amendedToUseApplicationIn",
    "useApplicationCurrentlyIn",
    "amendedToItuApplicationIn",
    "filingBasisFiledAs44DIn",
    "amendedTo44DApplicationIn",
    "filingBasisCurrent44DIn",
    "filingBasisFiledAs44EIn",
    "filingBasisCurrent44EIn",
    "amendedTo44EApplicationIn",
    "withoutBasisCurrentlyIn",
    "filingCurrentNoBasisIn",
    "colorDrawingFiledIn",
    "colorDrawingCurrentIn",
    "drawing3DFiledIn",
    "drawing3DCurrentIn",
    "standardCharactersClaimedIn",
    "filingBasisFiledAs66AIn",
    "filingBasisCurrent66AIn",
    "renewalDate",
    "lawOfficeAssignedLocationCode",
    "currentLocation",
    "locationDate",
    "employeeName"
})
@XmlRootElement(name = "case-file-header")
public class CaseFileHeader {

    @XmlElement(name = "filing-date")
    protected String filingDate;
    @XmlElement(name = "registration-date")
    protected String registrationDate;
    @XmlElement(name = "status-code")
    protected String statusCode;
    @XmlElement(name = "status-date")
    protected String statusDate;
    @XmlElement(name = "mark-identification")
    protected String markIdentification;
    @XmlElement(name = "mark-drawing-code")
    protected String markDrawingCode;
    @XmlElement(name = "published-for-opposition-date")
    protected String publishedForOppositionDate;
    @XmlElement(name = "amend-to-register-date")
    protected String amendToRegisterDate;
    @XmlElement(name = "abandonment-date")
    protected String abandonmentDate;
    @XmlElement(name = "cancellation-code")
    protected String cancellationCode;
    @XmlElement(name = "cancellation-date")
    protected String cancellationDate;
    @XmlElement(name = "republished-12c-date")
    protected String republished12CDate;
    @XmlElement(name = "domestic-representative-name")
    protected String domesticRepresentativeName;
    @XmlElement(name = "attorney-docket-number")
    protected String attorneyDocketNumber;
    @XmlElement(name = "attorney-name")
    protected String attorneyName;
    @XmlElement(name = "principal-register-amended-in")
    protected String principalRegisterAmendedIn;
    @XmlElement(name = "supplemental-register-amended-in")
    protected String supplementalRegisterAmendedIn;
    @XmlElement(name = "trademark-in")
    protected String trademarkIn;
    @XmlElement(name = "collective-trademark-in")
    protected String collectiveTrademarkIn;
    @XmlElement(name = "service-mark-in")
    protected String serviceMarkIn;
    @XmlElement(name = "collective-service-mark-in")
    protected String collectiveServiceMarkIn;
    @XmlElement(name = "collective-membership-mark-in")
    protected String collectiveMembershipMarkIn;
    @XmlElement(name = "certification-mark-in")
    protected String certificationMarkIn;
    @XmlElement(name = "cancellation-pending-in")
    protected String cancellationPendingIn;
    @XmlElement(name = "published-concurrent-in")
    protected String publishedConcurrentIn;
    @XmlElement(name = "concurrent-use-in")
    protected String concurrentUseIn;
    @XmlElement(name = "concurrent-use-proceeding-in")
    protected String concurrentUseProceedingIn;
    @XmlElement(name = "interference-pending-in")
    protected String interferencePendingIn;
    @XmlElement(name = "opposition-pending-in")
    protected String oppositionPendingIn;
    @XmlElement(name = "section-12c-in")
    protected String section12CIn;
    @XmlElement(name = "section-2f-in")
    protected String section2FIn;
    @XmlElement(name = "section-2f-in-part-in")
    protected String section2FInPartIn;
    @XmlElement(name = "renewal-filed-in")
    protected String renewalFiledIn;
    @XmlElement(name = "section-8-filed-in")
    protected String section8FiledIn;
    @XmlElement(name = "section-8-partial-accept-in")
    protected String section8PartialAcceptIn;
    @XmlElement(name = "section-8-accepted-in")
    protected String section8AcceptedIn;
    @XmlElement(name = "section-15-acknowledged-in")
    protected String section15AcknowledgedIn;
    @XmlElement(name = "section-15-filed-in")
    protected String section15FiledIn;
    @XmlElement(name = "supplemental-register-in")
    protected String supplementalRegisterIn;
    @XmlElement(name = "foreign-priority-in")
    protected String foreignPriorityIn;
    @XmlElement(name = "change-registration-in")
    protected String changeRegistrationIn;
    @XmlElement(name = "intent-to-use-in")
    protected String intentToUseIn;
    @XmlElement(name = "intent-to-use-current-in")
    protected String intentToUseCurrentIn;
    @XmlElement(name = "filed-as-use-application-in")
    protected String filedAsUseApplicationIn;
    @XmlElement(name = "amended-to-use-application-in")
    protected String amendedToUseApplicationIn;
    @XmlElement(name = "use-application-currently-in")
    protected String useApplicationCurrentlyIn;
    @XmlElement(name = "amended-to-itu-application-in")
    protected String amendedToItuApplicationIn;
    @XmlElement(name = "filing-basis-filed-as-44d-in")
    protected String filingBasisFiledAs44DIn;
    @XmlElement(name = "amended-to-44d-application-in")
    protected String amendedTo44DApplicationIn;
    @XmlElement(name = "filing-basis-current-44d-in")
    protected String filingBasisCurrent44DIn;
    @XmlElement(name = "filing-basis-filed-as-44e-in")
    protected String filingBasisFiledAs44EIn;
    @XmlElement(name = "filing-basis-current-44e-in")
    protected String filingBasisCurrent44EIn;
    @XmlElement(name = "amended-to-44e-application-in")
    protected String amendedTo44EApplicationIn;
    @XmlElement(name = "without-basis-currently-in")
    protected String withoutBasisCurrentlyIn;
    @XmlElement(name = "filing-current-no-basis-in")
    protected String filingCurrentNoBasisIn;
    @XmlElement(name = "color-drawing-filed-in")
    protected String colorDrawingFiledIn;
    @XmlElement(name = "color-drawing-current-in")
    protected String colorDrawingCurrentIn;
    @XmlElement(name = "drawing-3d-filed-in")
    protected String drawing3DFiledIn;
    @XmlElement(name = "drawing-3d-current-in")
    protected String drawing3DCurrentIn;
    @XmlElement(name = "standard-characters-claimed-in")
    protected String standardCharactersClaimedIn;
    @XmlElement(name = "filing-basis-filed-as-66a-in")
    protected String filingBasisFiledAs66AIn;
    @XmlElement(name = "filing-basis-current-66a-in")
    protected String filingBasisCurrent66AIn;
    @XmlElement(name = "renewal-date")
    protected String renewalDate;
    @XmlElement(name = "law-office-assigned-location-code")
    protected String lawOfficeAssignedLocationCode;
    @XmlElement(name = "current-location")
    protected String currentLocation;
    @XmlElement(name = "location-date")
    protected String locationDate;
    @XmlElement(name = "employee-name")
    protected String employeeName;

    /**
     * Gets the value of the filingDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFilingDate() {
        return filingDate;
    }

    /**
     * Sets the value of the filingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFilingDate(String value) {
        this.filingDate = value;
    }

    /**
     * Gets the value of the registrationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegistrationDate() {
        return registrationDate;
    }

    /**
     * Sets the value of the registrationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegistrationDate(String value) {
        this.registrationDate = value;
    }

    /**
     * Gets the value of the statusCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusCode() {
        return statusCode;
    }

    /**
     * Sets the value of the statusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusCode(String value) {
        this.statusCode = value;
    }

    /**
     * Gets the value of the statusDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusDate() {
        return statusDate;
    }

    /**
     * Sets the value of the statusDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusDate(String value) {
        this.statusDate = value;
    }

    /**
     * Gets the value of the markIdentification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarkIdentification() {
        return markIdentification;
    }

    /**
     * Sets the value of the markIdentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarkIdentification(String value) {
        this.markIdentification = value;
    }

    /**
     * Gets the value of the markDrawingCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarkDrawingCode() {
        return markDrawingCode;
    }

    /**
     * Sets the value of the markDrawingCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarkDrawingCode(String value) {
        this.markDrawingCode = value;
    }

    /**
     * Gets the value of the publishedForOppositionDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublishedForOppositionDate() {
        return publishedForOppositionDate;
    }

    /**
     * Sets the value of the publishedForOppositionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublishedForOppositionDate(String value) {
        this.publishedForOppositionDate = value;
    }

    /**
     * Gets the value of the amendToRegisterDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmendToRegisterDate() {
        return amendToRegisterDate;
    }

    /**
     * Sets the value of the amendToRegisterDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmendToRegisterDate(String value) {
        this.amendToRegisterDate = value;
    }

    /**
     * Gets the value of the abandonmentDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbandonmentDate() {
        return abandonmentDate;
    }

    /**
     * Sets the value of the abandonmentDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbandonmentDate(String value) {
        this.abandonmentDate = value;
    }

    /**
     * Gets the value of the cancellationCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCancellationCode() {
        return cancellationCode;
    }

    /**
     * Sets the value of the cancellationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCancellationCode(String value) {
        this.cancellationCode = value;
    }

    /**
     * Gets the value of the cancellationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCancellationDate() {
        return cancellationDate;
    }

    /**
     * Sets the value of the cancellationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCancellationDate(String value) {
        this.cancellationDate = value;
    }

    /**
     * Gets the value of the republished12CDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepublished12CDate() {
        return republished12CDate;
    }

    /**
     * Sets the value of the republished12CDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepublished12CDate(String value) {
        this.republished12CDate = value;
    }

    /**
     * Gets the value of the domesticRepresentativeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDomesticRepresentativeName() {
        return domesticRepresentativeName;
    }

    /**
     * Sets the value of the domesticRepresentativeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDomesticRepresentativeName(String value) {
        this.domesticRepresentativeName = value;
    }

    /**
     * Gets the value of the attorneyDocketNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttorneyDocketNumber() {
        return attorneyDocketNumber;
    }

    /**
     * Sets the value of the attorneyDocketNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttorneyDocketNumber(String value) {
        this.attorneyDocketNumber = value;
    }

    /**
     * Gets the value of the attorneyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAttorneyName() {
        return attorneyName;
    }

    /**
     * Sets the value of the attorneyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAttorneyName(String value) {
        this.attorneyName = value;
    }

    /**
     * Gets the value of the principalRegisterAmendedIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrincipalRegisterAmendedIn() {
        return principalRegisterAmendedIn;
    }

    /**
     * Sets the value of the principalRegisterAmendedIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrincipalRegisterAmendedIn(String value) {
        this.principalRegisterAmendedIn = value;
    }

    /**
     * Gets the value of the supplementalRegisterAmendedIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplementalRegisterAmendedIn() {
        return supplementalRegisterAmendedIn;
    }

    /**
     * Sets the value of the supplementalRegisterAmendedIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplementalRegisterAmendedIn(String value) {
        this.supplementalRegisterAmendedIn = value;
    }

    /**
     * Gets the value of the trademarkIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrademarkIn() {
        return trademarkIn;
    }

    /**
     * Sets the value of the trademarkIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrademarkIn(String value) {
        this.trademarkIn = value;
    }

    /**
     * Gets the value of the collectiveTrademarkIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCollectiveTrademarkIn() {
        return collectiveTrademarkIn;
    }

    /**
     * Sets the value of the collectiveTrademarkIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCollectiveTrademarkIn(String value) {
        this.collectiveTrademarkIn = value;
    }

    /**
     * Gets the value of the serviceMarkIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServiceMarkIn() {
        return serviceMarkIn;
    }

    /**
     * Sets the value of the serviceMarkIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServiceMarkIn(String value) {
        this.serviceMarkIn = value;
    }

    /**
     * Gets the value of the collectiveServiceMarkIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCollectiveServiceMarkIn() {
        return collectiveServiceMarkIn;
    }

    /**
     * Sets the value of the collectiveServiceMarkIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCollectiveServiceMarkIn(String value) {
        this.collectiveServiceMarkIn = value;
    }

    /**
     * Gets the value of the collectiveMembershipMarkIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCollectiveMembershipMarkIn() {
        return collectiveMembershipMarkIn;
    }

    /**
     * Sets the value of the collectiveMembershipMarkIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCollectiveMembershipMarkIn(String value) {
        this.collectiveMembershipMarkIn = value;
    }

    /**
     * Gets the value of the certificationMarkIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCertificationMarkIn() {
        return certificationMarkIn;
    }

    /**
     * Sets the value of the certificationMarkIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCertificationMarkIn(String value) {
        this.certificationMarkIn = value;
    }

    /**
     * Gets the value of the cancellationPendingIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCancellationPendingIn() {
        return cancellationPendingIn;
    }

    /**
     * Sets the value of the cancellationPendingIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCancellationPendingIn(String value) {
        this.cancellationPendingIn = value;
    }

    /**
     * Gets the value of the publishedConcurrentIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublishedConcurrentIn() {
        return publishedConcurrentIn;
    }

    /**
     * Sets the value of the publishedConcurrentIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublishedConcurrentIn(String value) {
        this.publishedConcurrentIn = value;
    }

    /**
     * Gets the value of the concurrentUseIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConcurrentUseIn() {
        return concurrentUseIn;
    }

    /**
     * Sets the value of the concurrentUseIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConcurrentUseIn(String value) {
        this.concurrentUseIn = value;
    }

    /**
     * Gets the value of the concurrentUseProceedingIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConcurrentUseProceedingIn() {
        return concurrentUseProceedingIn;
    }

    /**
     * Sets the value of the concurrentUseProceedingIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConcurrentUseProceedingIn(String value) {
        this.concurrentUseProceedingIn = value;
    }

    /**
     * Gets the value of the interferencePendingIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterferencePendingIn() {
        return interferencePendingIn;
    }

    /**
     * Sets the value of the interferencePendingIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterferencePendingIn(String value) {
        this.interferencePendingIn = value;
    }

    /**
     * Gets the value of the oppositionPendingIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOppositionPendingIn() {
        return oppositionPendingIn;
    }

    /**
     * Sets the value of the oppositionPendingIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOppositionPendingIn(String value) {
        this.oppositionPendingIn = value;
    }

    /**
     * Gets the value of the section12CIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSection12CIn() {
        return section12CIn;
    }

    /**
     * Sets the value of the section12CIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSection12CIn(String value) {
        this.section12CIn = value;
    }

    /**
     * Gets the value of the section2FIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSection2FIn() {
        return section2FIn;
    }

    /**
     * Sets the value of the section2FIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSection2FIn(String value) {
        this.section2FIn = value;
    }

    /**
     * Gets the value of the section2FInPartIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSection2FInPartIn() {
        return section2FInPartIn;
    }

    /**
     * Sets the value of the section2FInPartIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSection2FInPartIn(String value) {
        this.section2FInPartIn = value;
    }

    /**
     * Gets the value of the renewalFiledIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRenewalFiledIn() {
        return renewalFiledIn;
    }

    /**
     * Sets the value of the renewalFiledIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRenewalFiledIn(String value) {
        this.renewalFiledIn = value;
    }

    /**
     * Gets the value of the section8FiledIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSection8FiledIn() {
        return section8FiledIn;
    }

    /**
     * Sets the value of the section8FiledIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSection8FiledIn(String value) {
        this.section8FiledIn = value;
    }

    /**
     * Gets the value of the section8PartialAcceptIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSection8PartialAcceptIn() {
        return section8PartialAcceptIn;
    }

    /**
     * Sets the value of the section8PartialAcceptIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSection8PartialAcceptIn(String value) {
        this.section8PartialAcceptIn = value;
    }

    /**
     * Gets the value of the section8AcceptedIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSection8AcceptedIn() {
        return section8AcceptedIn;
    }

    /**
     * Sets the value of the section8AcceptedIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSection8AcceptedIn(String value) {
        this.section8AcceptedIn = value;
    }

    /**
     * Gets the value of the section15AcknowledgedIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSection15AcknowledgedIn() {
        return section15AcknowledgedIn;
    }

    /**
     * Sets the value of the section15AcknowledgedIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSection15AcknowledgedIn(String value) {
        this.section15AcknowledgedIn = value;
    }

    /**
     * Gets the value of the section15FiledIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSection15FiledIn() {
        return section15FiledIn;
    }

    /**
     * Sets the value of the section15FiledIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSection15FiledIn(String value) {
        this.section15FiledIn = value;
    }

    /**
     * Gets the value of the supplementalRegisterIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSupplementalRegisterIn() {
        return supplementalRegisterIn;
    }

    /**
     * Sets the value of the supplementalRegisterIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSupplementalRegisterIn(String value) {
        this.supplementalRegisterIn = value;
    }

    /**
     * Gets the value of the foreignPriorityIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForeignPriorityIn() {
        return foreignPriorityIn;
    }

    /**
     * Sets the value of the foreignPriorityIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForeignPriorityIn(String value) {
        this.foreignPriorityIn = value;
    }

    /**
     * Gets the value of the changeRegistrationIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChangeRegistrationIn() {
        return changeRegistrationIn;
    }

    /**
     * Sets the value of the changeRegistrationIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChangeRegistrationIn(String value) {
        this.changeRegistrationIn = value;
    }

    /**
     * Gets the value of the intentToUseIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntentToUseIn() {
        return intentToUseIn;
    }

    /**
     * Sets the value of the intentToUseIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntentToUseIn(String value) {
        this.intentToUseIn = value;
    }

    /**
     * Gets the value of the intentToUseCurrentIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIntentToUseCurrentIn() {
        return intentToUseCurrentIn;
    }

    /**
     * Sets the value of the intentToUseCurrentIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIntentToUseCurrentIn(String value) {
        this.intentToUseCurrentIn = value;
    }

    /**
     * Gets the value of the filedAsUseApplicationIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFiledAsUseApplicationIn() {
        return filedAsUseApplicationIn;
    }

    /**
     * Sets the value of the filedAsUseApplicationIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFiledAsUseApplicationIn(String value) {
        this.filedAsUseApplicationIn = value;
    }

    /**
     * Gets the value of the amendedToUseApplicationIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmendedToUseApplicationIn() {
        return amendedToUseApplicationIn;
    }

    /**
     * Sets the value of the amendedToUseApplicationIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmendedToUseApplicationIn(String value) {
        this.amendedToUseApplicationIn = value;
    }

    /**
     * Gets the value of the useApplicationCurrentlyIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUseApplicationCurrentlyIn() {
        return useApplicationCurrentlyIn;
    }

    /**
     * Sets the value of the useApplicationCurrentlyIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUseApplicationCurrentlyIn(String value) {
        this.useApplicationCurrentlyIn = value;
    }

    /**
     * Gets the value of the amendedToItuApplicationIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmendedToItuApplicationIn() {
        return amendedToItuApplicationIn;
    }

    /**
     * Sets the value of the amendedToItuApplicationIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmendedToItuApplicationIn(String value) {
        this.amendedToItuApplicationIn = value;
    }

    /**
     * Gets the value of the filingBasisFiledAs44DIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFilingBasisFiledAs44DIn() {
        return filingBasisFiledAs44DIn;
    }

    /**
     * Sets the value of the filingBasisFiledAs44DIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFilingBasisFiledAs44DIn(String value) {
        this.filingBasisFiledAs44DIn = value;
    }

    /**
     * Gets the value of the amendedTo44DApplicationIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmendedTo44DApplicationIn() {
        return amendedTo44DApplicationIn;
    }

    /**
     * Sets the value of the amendedTo44DApplicationIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmendedTo44DApplicationIn(String value) {
        this.amendedTo44DApplicationIn = value;
    }

    /**
     * Gets the value of the filingBasisCurrent44DIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFilingBasisCurrent44DIn() {
        return filingBasisCurrent44DIn;
    }

    /**
     * Sets the value of the filingBasisCurrent44DIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFilingBasisCurrent44DIn(String value) {
        this.filingBasisCurrent44DIn = value;
    }

    /**
     * Gets the value of the filingBasisFiledAs44EIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFilingBasisFiledAs44EIn() {
        return filingBasisFiledAs44EIn;
    }

    /**
     * Sets the value of the filingBasisFiledAs44EIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFilingBasisFiledAs44EIn(String value) {
        this.filingBasisFiledAs44EIn = value;
    }

    /**
     * Gets the value of the filingBasisCurrent44EIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFilingBasisCurrent44EIn() {
        return filingBasisCurrent44EIn;
    }

    /**
     * Sets the value of the filingBasisCurrent44EIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFilingBasisCurrent44EIn(String value) {
        this.filingBasisCurrent44EIn = value;
    }

    /**
     * Gets the value of the amendedTo44EApplicationIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmendedTo44EApplicationIn() {
        return amendedTo44EApplicationIn;
    }

    /**
     * Sets the value of the amendedTo44EApplicationIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmendedTo44EApplicationIn(String value) {
        this.amendedTo44EApplicationIn = value;
    }

    /**
     * Gets the value of the withoutBasisCurrentlyIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWithoutBasisCurrentlyIn() {
        return withoutBasisCurrentlyIn;
    }

    /**
     * Sets the value of the withoutBasisCurrentlyIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWithoutBasisCurrentlyIn(String value) {
        this.withoutBasisCurrentlyIn = value;
    }

    /**
     * Gets the value of the filingCurrentNoBasisIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFilingCurrentNoBasisIn() {
        return filingCurrentNoBasisIn;
    }

    /**
     * Sets the value of the filingCurrentNoBasisIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFilingCurrentNoBasisIn(String value) {
        this.filingCurrentNoBasisIn = value;
    }

    /**
     * Gets the value of the colorDrawingFiledIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColorDrawingFiledIn() {
        return colorDrawingFiledIn;
    }

    /**
     * Sets the value of the colorDrawingFiledIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColorDrawingFiledIn(String value) {
        this.colorDrawingFiledIn = value;
    }

    /**
     * Gets the value of the colorDrawingCurrentIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColorDrawingCurrentIn() {
        return colorDrawingCurrentIn;
    }

    /**
     * Sets the value of the colorDrawingCurrentIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColorDrawingCurrentIn(String value) {
        this.colorDrawingCurrentIn = value;
    }

    /**
     * Gets the value of the drawing3DFiledIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrawing3DFiledIn() {
        return drawing3DFiledIn;
    }

    /**
     * Sets the value of the drawing3DFiledIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrawing3DFiledIn(String value) {
        this.drawing3DFiledIn = value;
    }

    /**
     * Gets the value of the drawing3DCurrentIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDrawing3DCurrentIn() {
        return drawing3DCurrentIn;
    }

    /**
     * Sets the value of the drawing3DCurrentIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDrawing3DCurrentIn(String value) {
        this.drawing3DCurrentIn = value;
    }

    /**
     * Gets the value of the standardCharactersClaimedIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStandardCharactersClaimedIn() {
        return standardCharactersClaimedIn;
    }

    /**
     * Sets the value of the standardCharactersClaimedIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStandardCharactersClaimedIn(String value) {
        this.standardCharactersClaimedIn = value;
    }

    /**
     * Gets the value of the filingBasisFiledAs66AIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFilingBasisFiledAs66AIn() {
        return filingBasisFiledAs66AIn;
    }

    /**
     * Sets the value of the filingBasisFiledAs66AIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFilingBasisFiledAs66AIn(String value) {
        this.filingBasisFiledAs66AIn = value;
    }

    /**
     * Gets the value of the filingBasisCurrent66AIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFilingBasisCurrent66AIn() {
        return filingBasisCurrent66AIn;
    }

    /**
     * Sets the value of the filingBasisCurrent66AIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFilingBasisCurrent66AIn(String value) {
        this.filingBasisCurrent66AIn = value;
    }

    /**
     * Gets the value of the renewalDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRenewalDate() {
        return renewalDate;
    }

    /**
     * Sets the value of the renewalDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRenewalDate(String value) {
        this.renewalDate = value;
    }

    /**
     * Gets the value of the lawOfficeAssignedLocationCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLawOfficeAssignedLocationCode() {
        return lawOfficeAssignedLocationCode;
    }

    /**
     * Sets the value of the lawOfficeAssignedLocationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLawOfficeAssignedLocationCode(String value) {
        this.lawOfficeAssignedLocationCode = value;
    }

    /**
     * Gets the value of the currentLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCurrentLocation() {
        return currentLocation;
    }

    /**
     * Sets the value of the currentLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCurrentLocation(String value) {
        this.currentLocation = value;
    }

    /**
     * Gets the value of the locationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocationDate() {
        return locationDate;
    }

    /**
     * Sets the value of the locationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocationDate(String value) {
        this.locationDate = value;
    }

    /**
     * Gets the value of the employeeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmployeeName() {
        return employeeName;
    }

    /**
     * Sets the value of the employeeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmployeeName(String value) {
        this.employeeName = value;
    }

}
