//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.11 at 02:26:20 PM EEST 
//


package com.search.tm.utils.parse.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}international-code-total-no" minOccurs="0"/>
 *         &lt;element ref="{}us-code-total-no" minOccurs="0"/>
 *         &lt;element ref="{}international-code" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}us-code" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}status-code" minOccurs="0"/>
 *         &lt;element ref="{}status-date" minOccurs="0"/>
 *         &lt;element ref="{}first-use-anywhere-date" minOccurs="0"/>
 *         &lt;element ref="{}first-use-in-commerce-date" minOccurs="0"/>
 *         &lt;element ref="{}primary-code" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "internationalCodeTotalNo",
    "usCodeTotalNo",
    "internationalCode",
    "usCode",
    "statusCode",
    "statusDate",
    "firstUseAnywhereDate",
    "firstUseInCommerceDate",
    "primaryCode"
})
@XmlRootElement(name = "classification")
public class Classification {

    @XmlElement(name = "international-code-total-no")
    protected String internationalCodeTotalNo;
    @XmlElement(name = "us-code-total-no")
    protected String usCodeTotalNo;
    @XmlElement(name = "international-code")
    protected List<String> internationalCode;
    @XmlElement(name = "us-code")
    protected List<String> usCode;
    @XmlElement(name = "status-code")
    protected String statusCode;
    @XmlElement(name = "status-date")
    protected String statusDate;
    @XmlElement(name = "first-use-anywhere-date")
    protected String firstUseAnywhereDate;
    @XmlElement(name = "first-use-in-commerce-date")
    protected String firstUseInCommerceDate;
    @XmlElement(name = "primary-code")
    protected String primaryCode;

    /**
     * Gets the value of the internationalCodeTotalNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternationalCodeTotalNo() {
        return internationalCodeTotalNo;
    }

    /**
     * Sets the value of the internationalCodeTotalNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternationalCodeTotalNo(String value) {
        this.internationalCodeTotalNo = value;
    }

    /**
     * Gets the value of the usCodeTotalNo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsCodeTotalNo() {
        return usCodeTotalNo;
    }

    /**
     * Sets the value of the usCodeTotalNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsCodeTotalNo(String value) {
        this.usCodeTotalNo = value;
    }

    /**
     * Gets the value of the internationalCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the internationalCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInternationalCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getInternationalCode() {
        if (internationalCode == null) {
            internationalCode = new ArrayList<String>();
        }
        return this.internationalCode;
    }

    /**
     * Gets the value of the usCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the usCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUsCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getUsCode() {
        if (usCode == null) {
            usCode = new ArrayList<String>();
        }
        return this.usCode;
    }

    /**
     * Gets the value of the statusCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusCode() {
        return statusCode;
    }

    /**
     * Sets the value of the statusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusCode(String value) {
        this.statusCode = value;
    }

    /**
     * Gets the value of the statusDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusDate() {
        return statusDate;
    }

    /**
     * Sets the value of the statusDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusDate(String value) {
        this.statusDate = value;
    }

    /**
     * Gets the value of the firstUseAnywhereDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstUseAnywhereDate() {
        return firstUseAnywhereDate;
    }

    /**
     * Sets the value of the firstUseAnywhereDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstUseAnywhereDate(String value) {
        this.firstUseAnywhereDate = value;
    }

    /**
     * Gets the value of the firstUseInCommerceDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstUseInCommerceDate() {
        return firstUseInCommerceDate;
    }

    /**
     * Sets the value of the firstUseInCommerceDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstUseInCommerceDate(String value) {
        this.firstUseInCommerceDate = value;
    }

    /**
     * Gets the value of the primaryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimaryCode() {
        return primaryCode;
    }

    /**
     * Sets the value of the primaryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimaryCode(String value) {
        this.primaryCode = value;
    }

}
