//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.11 at 02:26:20 PM EEST 
//


package com.search.tm.utils.parse.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}international-registration-number"/>
 *         &lt;element ref="{}international-registration-date"/>
 *         &lt;element ref="{}international-publication-date"/>
 *         &lt;element ref="{}international-renewal-date"/>
 *         &lt;element ref="{}auto-protection-date"/>
 *         &lt;element ref="{}international-death-date" minOccurs="0"/>
 *         &lt;element ref="{}international-status-code"/>
 *         &lt;element ref="{}international-status-date"/>
 *         &lt;element ref="{}priority-claimed-in"/>
 *         &lt;element ref="{}priority-claimed-date" minOccurs="0"/>
 *         &lt;element ref="{}first-refusal-in"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "internationalRegistrationNumber",
    "internationalRegistrationDate",
    "internationalPublicationDate",
    "internationalRenewalDate",
    "autoProtectionDate",
    "internationalDeathDate",
    "internationalStatusCode",
    "internationalStatusDate",
    "priorityClaimedIn",
    "priorityClaimedDate",
    "firstRefusalIn"
})
@XmlRootElement(name = "international-registration")
public class InternationalRegistration {

    @XmlElement(name = "international-registration-number", required = true)
    protected String internationalRegistrationNumber;
    @XmlElement(name = "international-registration-date", required = true)
    protected String internationalRegistrationDate;
    @XmlElement(name = "international-publication-date", required = true)
    protected String internationalPublicationDate;
    @XmlElement(name = "international-renewal-date", required = true)
    protected String internationalRenewalDate;
    @XmlElement(name = "auto-protection-date", required = true)
    protected String autoProtectionDate;
    @XmlElement(name = "international-death-date")
    protected String internationalDeathDate;
    @XmlElement(name = "international-status-code", required = true)
    protected String internationalStatusCode;
    @XmlElement(name = "international-status-date", required = true)
    protected String internationalStatusDate;
    @XmlElement(name = "priority-claimed-in", required = true)
    protected String priorityClaimedIn;
    @XmlElement(name = "priority-claimed-date")
    protected String priorityClaimedDate;
    @XmlElement(name = "first-refusal-in", required = true)
    protected String firstRefusalIn;

    /**
     * Gets the value of the internationalRegistrationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternationalRegistrationNumber() {
        return internationalRegistrationNumber;
    }

    /**
     * Sets the value of the internationalRegistrationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternationalRegistrationNumber(String value) {
        this.internationalRegistrationNumber = value;
    }

    /**
     * Gets the value of the internationalRegistrationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternationalRegistrationDate() {
        return internationalRegistrationDate;
    }

    /**
     * Sets the value of the internationalRegistrationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternationalRegistrationDate(String value) {
        this.internationalRegistrationDate = value;
    }

    /**
     * Gets the value of the internationalPublicationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternationalPublicationDate() {
        return internationalPublicationDate;
    }

    /**
     * Sets the value of the internationalPublicationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternationalPublicationDate(String value) {
        this.internationalPublicationDate = value;
    }

    /**
     * Gets the value of the internationalRenewalDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternationalRenewalDate() {
        return internationalRenewalDate;
    }

    /**
     * Sets the value of the internationalRenewalDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternationalRenewalDate(String value) {
        this.internationalRenewalDate = value;
    }

    /**
     * Gets the value of the autoProtectionDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAutoProtectionDate() {
        return autoProtectionDate;
    }

    /**
     * Sets the value of the autoProtectionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAutoProtectionDate(String value) {
        this.autoProtectionDate = value;
    }

    /**
     * Gets the value of the internationalDeathDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternationalDeathDate() {
        return internationalDeathDate;
    }

    /**
     * Sets the value of the internationalDeathDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternationalDeathDate(String value) {
        this.internationalDeathDate = value;
    }

    /**
     * Gets the value of the internationalStatusCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternationalStatusCode() {
        return internationalStatusCode;
    }

    /**
     * Sets the value of the internationalStatusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternationalStatusCode(String value) {
        this.internationalStatusCode = value;
    }

    /**
     * Gets the value of the internationalStatusDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternationalStatusDate() {
        return internationalStatusDate;
    }

    /**
     * Sets the value of the internationalStatusDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternationalStatusDate(String value) {
        this.internationalStatusDate = value;
    }

    /**
     * Gets the value of the priorityClaimedIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriorityClaimedIn() {
        return priorityClaimedIn;
    }

    /**
     * Sets the value of the priorityClaimedIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriorityClaimedIn(String value) {
        this.priorityClaimedIn = value;
    }

    /**
     * Gets the value of the priorityClaimedDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPriorityClaimedDate() {
        return priorityClaimedDate;
    }

    /**
     * Sets the value of the priorityClaimedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPriorityClaimedDate(String value) {
        this.priorityClaimedDate = value;
    }

    /**
     * Gets the value of the firstRefusalIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstRefusalIn() {
        return firstRefusalIn;
    }

    /**
     * Sets the value of the firstRefusalIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstRefusalIn(String value) {
        this.firstRefusalIn = value;
    }

}
