//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.11 at 02:26:20 PM EEST 
//


package com.search.tm.utils.parse.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}entry-number"/>
 *         &lt;element ref="{}reference-number"/>
 *         &lt;element ref="{}original-filing-date-uspto"/>
 *         &lt;element ref="{}international-registration-number" minOccurs="0"/>
 *         &lt;element ref="{}international-registration-date" minOccurs="0"/>
 *         &lt;element ref="{}international-status-code" minOccurs="0"/>
 *         &lt;element ref="{}international-status-date" minOccurs="0"/>
 *         &lt;element ref="{}irregularity-reply-by-date" minOccurs="0"/>
 *         &lt;element ref="{}international-renewal-date" minOccurs="0"/>
 *         &lt;element ref="{}madrid-history-events" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "entryNumber",
    "referenceNumber",
    "originalFilingDateUspto",
    "internationalRegistrationNumber",
    "internationalRegistrationDate",
    "internationalStatusCode",
    "internationalStatusDate",
    "irregularityReplyByDate",
    "internationalRenewalDate",
    "madridHistoryEvents"
})
@XmlRootElement(name = "madrid-international-filing-record")
public class MadridInternationalFilingRecord {

    @XmlElement(name = "entry-number", required = true)
    protected String entryNumber;
    @XmlElement(name = "reference-number", required = true)
    protected String referenceNumber;
    @XmlElement(name = "original-filing-date-uspto", required = true)
    protected String originalFilingDateUspto;
    @XmlElement(name = "international-registration-number")
    protected String internationalRegistrationNumber;
    @XmlElement(name = "international-registration-date")
    protected String internationalRegistrationDate;
    @XmlElement(name = "international-status-code")
    protected String internationalStatusCode;
    @XmlElement(name = "international-status-date")
    protected String internationalStatusDate;
    @XmlElement(name = "irregularity-reply-by-date")
    protected String irregularityReplyByDate;
    @XmlElement(name = "international-renewal-date")
    protected String internationalRenewalDate;
    @XmlElement(name = "madrid-history-events")
    protected MadridHistoryEvents madridHistoryEvents;

    /**
     * Gets the value of the entryNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntryNumber() {
        return entryNumber;
    }

    /**
     * Sets the value of the entryNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntryNumber(String value) {
        this.entryNumber = value;
    }

    /**
     * Gets the value of the referenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferenceNumber() {
        return referenceNumber;
    }

    /**
     * Sets the value of the referenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferenceNumber(String value) {
        this.referenceNumber = value;
    }

    /**
     * Gets the value of the originalFilingDateUspto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginalFilingDateUspto() {
        return originalFilingDateUspto;
    }

    /**
     * Sets the value of the originalFilingDateUspto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginalFilingDateUspto(String value) {
        this.originalFilingDateUspto = value;
    }

    /**
     * Gets the value of the internationalRegistrationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternationalRegistrationNumber() {
        return internationalRegistrationNumber;
    }

    /**
     * Sets the value of the internationalRegistrationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternationalRegistrationNumber(String value) {
        this.internationalRegistrationNumber = value;
    }

    /**
     * Gets the value of the internationalRegistrationDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternationalRegistrationDate() {
        return internationalRegistrationDate;
    }

    /**
     * Sets the value of the internationalRegistrationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternationalRegistrationDate(String value) {
        this.internationalRegistrationDate = value;
    }

    /**
     * Gets the value of the internationalStatusCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternationalStatusCode() {
        return internationalStatusCode;
    }

    /**
     * Sets the value of the internationalStatusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternationalStatusCode(String value) {
        this.internationalStatusCode = value;
    }

    /**
     * Gets the value of the internationalStatusDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternationalStatusDate() {
        return internationalStatusDate;
    }

    /**
     * Sets the value of the internationalStatusDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternationalStatusDate(String value) {
        this.internationalStatusDate = value;
    }

    /**
     * Gets the value of the irregularityReplyByDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIrregularityReplyByDate() {
        return irregularityReplyByDate;
    }

    /**
     * Sets the value of the irregularityReplyByDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIrregularityReplyByDate(String value) {
        this.irregularityReplyByDate = value;
    }

    /**
     * Gets the value of the internationalRenewalDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternationalRenewalDate() {
        return internationalRenewalDate;
    }

    /**
     * Sets the value of the internationalRenewalDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternationalRenewalDate(String value) {
        this.internationalRenewalDate = value;
    }

    /**
     * Gets the value of the madridHistoryEvents property.
     * 
     * @return
     *     possible object is
     *     {@link MadridHistoryEvents }
     *     
     */
    public MadridHistoryEvents getMadridHistoryEvents() {
        return madridHistoryEvents;
    }

    /**
     * Sets the value of the madridHistoryEvents property.
     * 
     * @param value
     *     allowed object is
     *     {@link MadridHistoryEvents }
     *     
     */
    public void setMadridHistoryEvents(MadridHistoryEvents value) {
        this.madridHistoryEvents = value;
    }

}
