//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.11 at 02:26:20 PM EEST 
//


package com.search.tm.utils.parse.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PublishedForOppositionDate_QNAME = new QName("", "published-for-opposition-date");
    private final static QName _SupplementalRegisterIn_QNAME = new QName("", "supplemental-register-in");
    private final static QName _PublishedConcurrentIn_QNAME = new QName("", "published-concurrent-in");
    private final static QName _InternationalRegistrationDate_QNAME = new QName("", "international-registration-date");
    private final static QName _ActionKey_QNAME = new QName("", "action-key");
    private final static QName _IntentToUseCurrentIn_QNAME = new QName("", "intent-to-use-current-in");
    private final static QName _Type_QNAME = new QName("", "type");
    private final static QName _FilingDate_QNAME = new QName("", "filing-date");
    private final static QName _Number_QNAME = new QName("", "number");
    private final static QName _PriorityClaimedDate_QNAME = new QName("", "priority-claimed-date");
    private final static QName _PartyType_QNAME = new QName("", "party-type");
    private final static QName _MarkIdentification_QNAME = new QName("", "mark-identification");
    private final static QName _AmendedToUseApplicationIn_QNAME = new QName("", "amended-to-use-application-in");
    private final static QName _PrimaryCode_QNAME = new QName("", "primary-code");
    private final static QName _ServiceMarkIn_QNAME = new QName("", "service-mark-in");
    private final static QName _InternationalPublicationDate_QNAME = new QName("", "international-publication-date");
    private final static QName _Text_QNAME = new QName("", "text");
    private final static QName _State_QNAME = new QName("", "state");
    private final static QName _CollectiveServiceMarkIn_QNAME = new QName("", "collective-service-mark-in");
    private final static QName _EmployeeName_QNAME = new QName("", "employee-name");
    private final static QName _RenewalDate_QNAME = new QName("", "renewal-date");
    private final static QName _DbaAkaText_QNAME = new QName("", "dba-aka-text");
    private final static QName _IrregularityReplyByDate_QNAME = new QName("", "irregularity-reply-by-date");
    private final static QName _DescriptionText_QNAME = new QName("", "description-text");
    private final static QName _FilingBasisCurrent66AIn_QNAME = new QName("", "filing-basis-current-66a-in");
    private final static QName _FileSegment_QNAME = new QName("", "file-segment");
    private final static QName _ColorDrawingFiledIn_QNAME = new QName("", "color-drawing-filed-in");
    private final static QName _AttorneyDocketNumber_QNAME = new QName("", "attorney-docket-number");
    private final static QName _InternationalRegistrationNumber_QNAME = new QName("", "international-registration-number");
    private final static QName _Section2FIn_QNAME = new QName("", "section-2f-in");
    private final static QName _InternationalStatusDate_QNAME = new QName("", "international-status-date");
    private final static QName _ComposedOfStatement_QNAME = new QName("", "composed-of-statement");
    private final static QName _RegistrationRenewalExpirationDate_QNAME = new QName("", "registration-renewal-expiration-date");
    private final static QName _CertificationMarkIn_QNAME = new QName("", "certification-mark-in");
    private final static QName _Other_QNAME = new QName("", "other");
    private final static QName _RegistrationDate_QNAME = new QName("", "registration-date");
    private final static QName _StandardCharactersClaimedIn_QNAME = new QName("", "standard-characters-claimed-in");
    private final static QName _City_QNAME = new QName("", "city");
    private final static QName _PriorityClaimedIn_QNAME = new QName("", "priority-claimed-in");
    private final static QName _AmendedTo44EApplicationIn_QNAME = new QName("", "amended-to-44e-application-in");
    private final static QName _UsCodeTotalNo_QNAME = new QName("", "us-code-total-no");
    private final static QName _EntityStatement_QNAME = new QName("", "entity-statement");
    private final static QName _CurrentLocation_QNAME = new QName("", "current-location");
    private final static QName _RegistrationRenewalDate_QNAME = new QName("", "registration-renewal-date");
    private final static QName _Drawing3DFiledIn_QNAME = new QName("", "drawing-3d-filed-in");
    private final static QName _InternationalRenewalDate_QNAME = new QName("", "international-renewal-date");
    private final static QName _EntryNumber_QNAME = new QName("", "entry-number");
    private final static QName _LegalEntityTypeCode_QNAME = new QName("", "legal-entity-type-code");
    private final static QName _Section12CIn_QNAME = new QName("", "section-12c-in");
    private final static QName _DomesticRepresentativeName_QNAME = new QName("", "domestic-representative-name");
    private final static QName _WithoutBasisCurrentlyIn_QNAME = new QName("", "without-basis-currently-in");
    private final static QName _Section8AcceptedIn_QNAME = new QName("", "section-8-accepted-in");
    private final static QName _Republished12CDate_QNAME = new QName("", "republished-12c-date");
    private final static QName _FilingBasisFiledAs44EIn_QNAME = new QName("", "filing-basis-filed-as-44e-in");
    private final static QName _Section8PartialAcceptIn_QNAME = new QName("", "section-8-partial-accept-in");
    private final static QName _OriginalFilingDateUspto_QNAME = new QName("", "original-filing-date-uspto");
    private final static QName _ColorDrawingCurrentIn_QNAME = new QName("", "color-drawing-current-in");
    private final static QName _FirstUseAnywhereDate_QNAME = new QName("", "first-use-anywhere-date");
    private final static QName _Section8FiledIn_QNAME = new QName("", "section-8-filed-in");
    private final static QName _Date_QNAME = new QName("", "date");
    private final static QName _TrademarkIn_QNAME = new QName("", "trademark-in");
    private final static QName _InternationalCodeTotalNo_QNAME = new QName("", "international-code-total-no");
    private final static QName _OtherRelatedIn_QNAME = new QName("", "other-related-in");
    private final static QName _Country_QNAME = new QName("", "country");
    private final static QName _Section15FiledIn_QNAME = new QName("", "section-15-filed-in");
    private final static QName _CreationDatetime_QNAME = new QName("", "creation-datetime");
    private final static QName _RegistrationNumber_QNAME = new QName("", "registration-number");
    private final static QName _TypeCode_QNAME = new QName("", "type-code");
    private final static QName _FilingBasisCurrent44DIn_QNAME = new QName("", "filing-basis-current-44d-in");
    private final static QName _ApplicationNumber_QNAME = new QName("", "application-number");
    private final static QName _Section2FInPartIn_QNAME = new QName("", "section-2f-in-part-in");
    private final static QName _PrincipalRegisterAmendedIn_QNAME = new QName("", "principal-register-amended-in");
    private final static QName _ReferenceNumber_QNAME = new QName("", "reference-number");
    private final static QName _Section15AcknowledgedIn_QNAME = new QName("", "section-15-acknowledged-in");
    private final static QName _ForeignPriorityClaimIn_QNAME = new QName("", "foreign-priority-claim-in");
    private final static QName _CollectiveTrademarkIn_QNAME = new QName("", "collective-trademark-in");
    private final static QName _RelationshipType_QNAME = new QName("", "relationship-type");
    private final static QName _DataAvailableCode_QNAME = new QName("", "data-available-code");
    private final static QName _VersionDate_QNAME = new QName("", "version-date");
    private final static QName _MarkDrawingCode_QNAME = new QName("", "mark-drawing-code");
    private final static QName _UsCode_QNAME = new QName("", "us-code");
    private final static QName _Postcode_QNAME = new QName("", "postcode");
    private final static QName _FirstRefusalIn_QNAME = new QName("", "first-refusal-in");
    private final static QName _RenewalFiledIn_QNAME = new QName("", "renewal-filed-in");
    private final static QName _ForeignPriorityIn_QNAME = new QName("", "foreign-priority-in");
    private final static QName _StatusDate_QNAME = new QName("", "status-date");
    private final static QName _FilingBasisFiledAs66AIn_QNAME = new QName("", "filing-basis-filed-as-66a-in");
    private final static QName _TransactionDate_QNAME = new QName("", "transaction-date");
    private final static QName _InterferencePendingIn_QNAME = new QName("", "interference-pending-in");
    private final static QName _Address1_QNAME = new QName("", "address-1");
    private final static QName _OppositionPendingIn_QNAME = new QName("", "opposition-pending-in");
    private final static QName _ChangeRegistrationIn_QNAME = new QName("", "change-registration-in");
    private final static QName _Address2_QNAME = new QName("", "address-2");
    private final static QName _AmendedTo44DApplicationIn_QNAME = new QName("", "amended-to-44d-application-in");
    private final static QName _Address3_QNAME = new QName("", "address-3");
    private final static QName _Address4_QNAME = new QName("", "address-4");
    private final static QName _CancellationDate_QNAME = new QName("", "cancellation-date");
    private final static QName _FirstUseInCommerceDate_QNAME = new QName("", "first-use-in-commerce-date");
    private final static QName _Address5_QNAME = new QName("", "address-5");
    private final static QName _IntentToUseIn_QNAME = new QName("", "intent-to-use-in");
    private final static QName _PartyName_QNAME = new QName("", "party-name");
    private final static QName _Code_QNAME = new QName("", "code");
    private final static QName _ConcurrentUseProceedingIn_QNAME = new QName("", "concurrent-use-proceeding-in");
    private final static QName _CollectiveMembershipMarkIn_QNAME = new QName("", "collective-membership-mark-in");
    private final static QName _LawOfficeAssignedLocationCode_QNAME = new QName("", "law-office-assigned-location-code");
    private final static QName _AttorneyName_QNAME = new QName("", "attorney-name");
    private final static QName _AbandonmentDate_QNAME = new QName("", "abandonment-date");
    private final static QName _FilingBasisFiledAs44DIn_QNAME = new QName("", "filing-basis-filed-as-44d-in");
    private final static QName _Drawing3DCurrentIn_QNAME = new QName("", "drawing-3d-current-in");
    private final static QName _FiledAsUseApplicationIn_QNAME = new QName("", "filed-as-use-application-in");
    private final static QName _RenewalNumber_QNAME = new QName("", "renewal-number");
    private final static QName _AutoProtectionDate_QNAME = new QName("", "auto-protection-date");
    private final static QName _VersionNo_QNAME = new QName("", "version-no");
    private final static QName _ConcurrentUseIn_QNAME = new QName("", "concurrent-use-in");
    private final static QName _NameChangeExplanation_QNAME = new QName("", "name-change-explanation");
    private final static QName _SerialNumber_QNAME = new QName("", "serial-number");
    private final static QName _SupplementalRegisterAmendedIn_QNAME = new QName("", "supplemental-register-amended-in");
    private final static QName _AmendedToItuApplicationIn_QNAME = new QName("", "amended-to-itu-application-in");
    private final static QName _LocationDate_QNAME = new QName("", "location-date");
    private final static QName _InternationalDeathDate_QNAME = new QName("", "international-death-date");
    private final static QName _FilingBasisCurrent44EIn_QNAME = new QName("", "filing-basis-current-44e-in");
    private final static QName _AmendToRegisterDate_QNAME = new QName("", "amend-to-register-date");
    private final static QName _FilingCurrentNoBasisIn_QNAME = new QName("", "filing-current-no-basis-in");
    private final static QName _StatusCode_QNAME = new QName("", "status-code");
    private final static QName _CancellationPendingIn_QNAME = new QName("", "cancellation-pending-in");
    private final static QName _CancellationCode_QNAME = new QName("", "cancellation-code");
    private final static QName _RegistrationExpirationDate_QNAME = new QName("", "registration-expiration-date");
    private final static QName _InternationalCode_QNAME = new QName("", "international-code");
    private final static QName _InternationalStatusCode_QNAME = new QName("", "international-status-code");
    private final static QName _UseApplicationCurrentlyIn_QNAME = new QName("", "use-application-currently-in");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DesignSearches }
     * 
     */
    public DesignSearches createDesignSearches() {
        return new DesignSearches();
    }

    /**
     * Create an instance of {@link DesignSearch }
     * 
     */
    public DesignSearch createDesignSearch() {
        return new DesignSearch();
    }

    /**
     * Create an instance of {@link MadridHistoryEvent }
     * 
     */
    public MadridHistoryEvent createMadridHistoryEvent() {
        return new MadridHistoryEvent();
    }

    /**
     * Create an instance of {@link TrademarkApplicationsDaily }
     * 
     */
    public TrademarkApplicationsDaily createTrademarkApplicationsDaily() {
        return new TrademarkApplicationsDaily();
    }

    /**
     * Create an instance of {@link Version }
     * 
     */
    public Version createVersion() {
        return new Version();
    }

    /**
     * Create an instance of {@link ApplicationInformation }
     * 
     */
    public ApplicationInformation createApplicationInformation() {
        return new ApplicationInformation();
    }

    /**
     * Create an instance of {@link FileSegments }
     * 
     */
    public FileSegments createFileSegments() {
        return new FileSegments();
    }

    /**
     * Create an instance of {@link ActionKeys }
     * 
     */
    public ActionKeys createActionKeys() {
        return new ActionKeys();
    }

    /**
     * Create an instance of {@link CaseFile }
     * 
     */
    public CaseFile createCaseFile() {
        return new CaseFile();
    }

    /**
     * Create an instance of {@link CaseFileHeader }
     * 
     */
    public CaseFileHeader createCaseFileHeader() {
        return new CaseFileHeader();
    }

    /**
     * Create an instance of {@link CaseFileStatements }
     * 
     */
    public CaseFileStatements createCaseFileStatements() {
        return new CaseFileStatements();
    }

    /**
     * Create an instance of {@link CaseFileStatement }
     * 
     */
    public CaseFileStatement createCaseFileStatement() {
        return new CaseFileStatement();
    }

    /**
     * Create an instance of {@link CaseFileEventStatements }
     * 
     */
    public CaseFileEventStatements createCaseFileEventStatements() {
        return new CaseFileEventStatements();
    }

    /**
     * Create an instance of {@link CaseFileEventStatement }
     * 
     */
    public CaseFileEventStatement createCaseFileEventStatement() {
        return new CaseFileEventStatement();
    }

    /**
     * Create an instance of {@link PriorRegistrationApplications }
     * 
     */
    public PriorRegistrationApplications createPriorRegistrationApplications() {
        return new PriorRegistrationApplications();
    }

    /**
     * Create an instance of {@link PriorRegistrationApplication }
     * 
     */
    public PriorRegistrationApplication createPriorRegistrationApplication() {
        return new PriorRegistrationApplication();
    }

    /**
     * Create an instance of {@link ForeignApplications }
     * 
     */
    public ForeignApplications createForeignApplications() {
        return new ForeignApplications();
    }

    /**
     * Create an instance of {@link ForeignApplication }
     * 
     */
    public ForeignApplication createForeignApplication() {
        return new ForeignApplication();
    }

    /**
     * Create an instance of {@link Classifications }
     * 
     */
    public Classifications createClassifications() {
        return new Classifications();
    }

    /**
     * Create an instance of {@link Classification }
     * 
     */
    public Classification createClassification() {
        return new Classification();
    }

    /**
     * Create an instance of {@link Correspondent }
     * 
     */
    public Correspondent createCorrespondent() {
        return new Correspondent();
    }

    /**
     * Create an instance of {@link CaseFileOwners }
     * 
     */
    public CaseFileOwners createCaseFileOwners() {
        return new CaseFileOwners();
    }

    /**
     * Create an instance of {@link CaseFileOwner }
     * 
     */
    public CaseFileOwner createCaseFileOwner() {
        return new CaseFileOwner();
    }

    /**
     * Create an instance of {@link Nationality }
     * 
     */
    public Nationality createNationality() {
        return new Nationality();
    }

    /**
     * Create an instance of {@link InternationalRegistration }
     * 
     */
    public InternationalRegistration createInternationalRegistration() {
        return new InternationalRegistration();
    }

    /**
     * Create an instance of {@link MadridInternationalFilingRequests }
     * 
     */
    public MadridInternationalFilingRequests createMadridInternationalFilingRequests() {
        return new MadridInternationalFilingRequests();
    }

    /**
     * Create an instance of {@link MadridInternationalFilingRecord }
     * 
     */
    public MadridInternationalFilingRecord createMadridInternationalFilingRecord() {
        return new MadridInternationalFilingRecord();
    }

    /**
     * Create an instance of {@link MadridHistoryEvents }
     * 
     */
    public MadridHistoryEvents createMadridHistoryEvents() {
        return new MadridHistoryEvents();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "published-for-opposition-date")
    public JAXBElement<String> createPublishedForOppositionDate(String value) {
        return new JAXBElement<String>(_PublishedForOppositionDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "supplemental-register-in")
    public JAXBElement<String> createSupplementalRegisterIn(String value) {
        return new JAXBElement<String>(_SupplementalRegisterIn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "published-concurrent-in")
    public JAXBElement<String> createPublishedConcurrentIn(String value) {
        return new JAXBElement<String>(_PublishedConcurrentIn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "international-registration-date")
    public JAXBElement<String> createInternationalRegistrationDate(String value) {
        return new JAXBElement<String>(_InternationalRegistrationDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "action-key")
    public JAXBElement<String> createActionKey(String value) {
        return new JAXBElement<String>(_ActionKey_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "intent-to-use-current-in")
    public JAXBElement<String> createIntentToUseCurrentIn(String value) {
        return new JAXBElement<String>(_IntentToUseCurrentIn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "type")
    public JAXBElement<String> createType(String value) {
        return new JAXBElement<String>(_Type_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "filing-date")
    public JAXBElement<String> createFilingDate(String value) {
        return new JAXBElement<String>(_FilingDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "number")
    public JAXBElement<String> createNumber(String value) {
        return new JAXBElement<String>(_Number_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "priority-claimed-date")
    public JAXBElement<String> createPriorityClaimedDate(String value) {
        return new JAXBElement<String>(_PriorityClaimedDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "party-type")
    public JAXBElement<String> createPartyType(String value) {
        return new JAXBElement<String>(_PartyType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mark-identification")
    public JAXBElement<String> createMarkIdentification(String value) {
        return new JAXBElement<String>(_MarkIdentification_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "amended-to-use-application-in")
    public JAXBElement<String> createAmendedToUseApplicationIn(String value) {
        return new JAXBElement<String>(_AmendedToUseApplicationIn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "primary-code")
    public JAXBElement<String> createPrimaryCode(String value) {
        return new JAXBElement<String>(_PrimaryCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "service-mark-in")
    public JAXBElement<String> createServiceMarkIn(String value) {
        return new JAXBElement<String>(_ServiceMarkIn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "international-publication-date")
    public JAXBElement<String> createInternationalPublicationDate(String value) {
        return new JAXBElement<String>(_InternationalPublicationDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "text")
    public JAXBElement<String> createText(String value) {
        return new JAXBElement<String>(_Text_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "state")
    public JAXBElement<String> createState(String value) {
        return new JAXBElement<String>(_State_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "collective-service-mark-in")
    public JAXBElement<String> createCollectiveServiceMarkIn(String value) {
        return new JAXBElement<String>(_CollectiveServiceMarkIn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "employee-name")
    public JAXBElement<String> createEmployeeName(String value) {
        return new JAXBElement<String>(_EmployeeName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "renewal-date")
    public JAXBElement<String> createRenewalDate(String value) {
        return new JAXBElement<String>(_RenewalDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dba-aka-text")
    public JAXBElement<String> createDbaAkaText(String value) {
        return new JAXBElement<String>(_DbaAkaText_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "irregularity-reply-by-date")
    public JAXBElement<String> createIrregularityReplyByDate(String value) {
        return new JAXBElement<String>(_IrregularityReplyByDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "description-text")
    public JAXBElement<String> createDescriptionText(String value) {
        return new JAXBElement<String>(_DescriptionText_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "filing-basis-current-66a-in")
    public JAXBElement<String> createFilingBasisCurrent66AIn(String value) {
        return new JAXBElement<String>(_FilingBasisCurrent66AIn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "file-segment")
    public JAXBElement<String> createFileSegment(String value) {
        return new JAXBElement<String>(_FileSegment_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "color-drawing-filed-in")
    public JAXBElement<String> createColorDrawingFiledIn(String value) {
        return new JAXBElement<String>(_ColorDrawingFiledIn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "attorney-docket-number")
    public JAXBElement<String> createAttorneyDocketNumber(String value) {
        return new JAXBElement<String>(_AttorneyDocketNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "international-registration-number")
    public JAXBElement<String> createInternationalRegistrationNumber(String value) {
        return new JAXBElement<String>(_InternationalRegistrationNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "section-2f-in")
    public JAXBElement<String> createSection2FIn(String value) {
        return new JAXBElement<String>(_Section2FIn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "international-status-date")
    public JAXBElement<String> createInternationalStatusDate(String value) {
        return new JAXBElement<String>(_InternationalStatusDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "composed-of-statement")
    public JAXBElement<String> createComposedOfStatement(String value) {
        return new JAXBElement<String>(_ComposedOfStatement_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "registration-renewal-expiration-date")
    public JAXBElement<String> createRegistrationRenewalExpirationDate(String value) {
        return new JAXBElement<String>(_RegistrationRenewalExpirationDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "certification-mark-in")
    public JAXBElement<String> createCertificationMarkIn(String value) {
        return new JAXBElement<String>(_CertificationMarkIn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "other")
    public JAXBElement<String> createOther(String value) {
        return new JAXBElement<String>(_Other_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "registration-date")
    public JAXBElement<String> createRegistrationDate(String value) {
        return new JAXBElement<String>(_RegistrationDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "standard-characters-claimed-in")
    public JAXBElement<String> createStandardCharactersClaimedIn(String value) {
        return new JAXBElement<String>(_StandardCharactersClaimedIn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "city")
    public JAXBElement<String> createCity(String value) {
        return new JAXBElement<String>(_City_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "priority-claimed-in")
    public JAXBElement<String> createPriorityClaimedIn(String value) {
        return new JAXBElement<String>(_PriorityClaimedIn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "amended-to-44e-application-in")
    public JAXBElement<String> createAmendedTo44EApplicationIn(String value) {
        return new JAXBElement<String>(_AmendedTo44EApplicationIn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "us-code-total-no")
    public JAXBElement<String> createUsCodeTotalNo(String value) {
        return new JAXBElement<String>(_UsCodeTotalNo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "entity-statement")
    public JAXBElement<String> createEntityStatement(String value) {
        return new JAXBElement<String>(_EntityStatement_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "current-location")
    public JAXBElement<String> createCurrentLocation(String value) {
        return new JAXBElement<String>(_CurrentLocation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "registration-renewal-date")
    public JAXBElement<String> createRegistrationRenewalDate(String value) {
        return new JAXBElement<String>(_RegistrationRenewalDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "drawing-3d-filed-in")
    public JAXBElement<String> createDrawing3DFiledIn(String value) {
        return new JAXBElement<String>(_Drawing3DFiledIn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "international-renewal-date")
    public JAXBElement<String> createInternationalRenewalDate(String value) {
        return new JAXBElement<String>(_InternationalRenewalDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "entry-number")
    public JAXBElement<String> createEntryNumber(String value) {
        return new JAXBElement<String>(_EntryNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "legal-entity-type-code")
    public JAXBElement<String> createLegalEntityTypeCode(String value) {
        return new JAXBElement<String>(_LegalEntityTypeCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "section-12c-in")
    public JAXBElement<String> createSection12CIn(String value) {
        return new JAXBElement<String>(_Section12CIn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "domestic-representative-name")
    public JAXBElement<String> createDomesticRepresentativeName(String value) {
        return new JAXBElement<String>(_DomesticRepresentativeName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "without-basis-currently-in")
    public JAXBElement<String> createWithoutBasisCurrentlyIn(String value) {
        return new JAXBElement<String>(_WithoutBasisCurrentlyIn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "section-8-accepted-in")
    public JAXBElement<String> createSection8AcceptedIn(String value) {
        return new JAXBElement<String>(_Section8AcceptedIn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "republished-12c-date")
    public JAXBElement<String> createRepublished12CDate(String value) {
        return new JAXBElement<String>(_Republished12CDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "filing-basis-filed-as-44e-in")
    public JAXBElement<String> createFilingBasisFiledAs44EIn(String value) {
        return new JAXBElement<String>(_FilingBasisFiledAs44EIn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "section-8-partial-accept-in")
    public JAXBElement<String> createSection8PartialAcceptIn(String value) {
        return new JAXBElement<String>(_Section8PartialAcceptIn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "original-filing-date-uspto")
    public JAXBElement<String> createOriginalFilingDateUspto(String value) {
        return new JAXBElement<String>(_OriginalFilingDateUspto_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "color-drawing-current-in")
    public JAXBElement<String> createColorDrawingCurrentIn(String value) {
        return new JAXBElement<String>(_ColorDrawingCurrentIn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "first-use-anywhere-date")
    public JAXBElement<String> createFirstUseAnywhereDate(String value) {
        return new JAXBElement<String>(_FirstUseAnywhereDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "section-8-filed-in")
    public JAXBElement<String> createSection8FiledIn(String value) {
        return new JAXBElement<String>(_Section8FiledIn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "date")
    public JAXBElement<String> createDate(String value) {
        return new JAXBElement<String>(_Date_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "trademark-in")
    public JAXBElement<String> createTrademarkIn(String value) {
        return new JAXBElement<String>(_TrademarkIn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "international-code-total-no")
    public JAXBElement<String> createInternationalCodeTotalNo(String value) {
        return new JAXBElement<String>(_InternationalCodeTotalNo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "other-related-in")
    public JAXBElement<String> createOtherRelatedIn(String value) {
        return new JAXBElement<String>(_OtherRelatedIn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "country")
    public JAXBElement<String> createCountry(String value) {
        return new JAXBElement<String>(_Country_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "section-15-filed-in")
    public JAXBElement<String> createSection15FiledIn(String value) {
        return new JAXBElement<String>(_Section15FiledIn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "creation-datetime")
    public JAXBElement<String> createCreationDatetime(String value) {
        return new JAXBElement<String>(_CreationDatetime_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "registration-number")
    public JAXBElement<String> createRegistrationNumber(String value) {
        return new JAXBElement<String>(_RegistrationNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "type-code")
    public JAXBElement<String> createTypeCode(String value) {
        return new JAXBElement<String>(_TypeCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "filing-basis-current-44d-in")
    public JAXBElement<String> createFilingBasisCurrent44DIn(String value) {
        return new JAXBElement<String>(_FilingBasisCurrent44DIn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "application-number")
    public JAXBElement<String> createApplicationNumber(String value) {
        return new JAXBElement<String>(_ApplicationNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "section-2f-in-part-in")
    public JAXBElement<String> createSection2FInPartIn(String value) {
        return new JAXBElement<String>(_Section2FInPartIn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "principal-register-amended-in")
    public JAXBElement<String> createPrincipalRegisterAmendedIn(String value) {
        return new JAXBElement<String>(_PrincipalRegisterAmendedIn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "reference-number")
    public JAXBElement<String> createReferenceNumber(String value) {
        return new JAXBElement<String>(_ReferenceNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "section-15-acknowledged-in")
    public JAXBElement<String> createSection15AcknowledgedIn(String value) {
        return new JAXBElement<String>(_Section15AcknowledgedIn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "foreign-priority-claim-in")
    public JAXBElement<String> createForeignPriorityClaimIn(String value) {
        return new JAXBElement<String>(_ForeignPriorityClaimIn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "collective-trademark-in")
    public JAXBElement<String> createCollectiveTrademarkIn(String value) {
        return new JAXBElement<String>(_CollectiveTrademarkIn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "relationship-type")
    public JAXBElement<String> createRelationshipType(String value) {
        return new JAXBElement<String>(_RelationshipType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "data-available-code")
    public JAXBElement<String> createDataAvailableCode(String value) {
        return new JAXBElement<String>(_DataAvailableCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "version-date")
    public JAXBElement<String> createVersionDate(String value) {
        return new JAXBElement<String>(_VersionDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "mark-drawing-code")
    public JAXBElement<String> createMarkDrawingCode(String value) {
        return new JAXBElement<String>(_MarkDrawingCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "us-code")
    public JAXBElement<String> createUsCode(String value) {
        return new JAXBElement<String>(_UsCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "postcode")
    public JAXBElement<String> createPostcode(String value) {
        return new JAXBElement<String>(_Postcode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "first-refusal-in")
    public JAXBElement<String> createFirstRefusalIn(String value) {
        return new JAXBElement<String>(_FirstRefusalIn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "renewal-filed-in")
    public JAXBElement<String> createRenewalFiledIn(String value) {
        return new JAXBElement<String>(_RenewalFiledIn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "foreign-priority-in")
    public JAXBElement<String> createForeignPriorityIn(String value) {
        return new JAXBElement<String>(_ForeignPriorityIn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "status-date")
    public JAXBElement<String> createStatusDate(String value) {
        return new JAXBElement<String>(_StatusDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "filing-basis-filed-as-66a-in")
    public JAXBElement<String> createFilingBasisFiledAs66AIn(String value) {
        return new JAXBElement<String>(_FilingBasisFiledAs66AIn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "transaction-date")
    public JAXBElement<String> createTransactionDate(String value) {
        return new JAXBElement<String>(_TransactionDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "interference-pending-in")
    public JAXBElement<String> createInterferencePendingIn(String value) {
        return new JAXBElement<String>(_InterferencePendingIn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "address-1")
    public JAXBElement<String> createAddress1(String value) {
        return new JAXBElement<String>(_Address1_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "opposition-pending-in")
    public JAXBElement<String> createOppositionPendingIn(String value) {
        return new JAXBElement<String>(_OppositionPendingIn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "change-registration-in")
    public JAXBElement<String> createChangeRegistrationIn(String value) {
        return new JAXBElement<String>(_ChangeRegistrationIn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "address-2")
    public JAXBElement<String> createAddress2(String value) {
        return new JAXBElement<String>(_Address2_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "amended-to-44d-application-in")
    public JAXBElement<String> createAmendedTo44DApplicationIn(String value) {
        return new JAXBElement<String>(_AmendedTo44DApplicationIn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "address-3")
    public JAXBElement<String> createAddress3(String value) {
        return new JAXBElement<String>(_Address3_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "address-4")
    public JAXBElement<String> createAddress4(String value) {
        return new JAXBElement<String>(_Address4_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "cancellation-date")
    public JAXBElement<String> createCancellationDate(String value) {
        return new JAXBElement<String>(_CancellationDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "first-use-in-commerce-date")
    public JAXBElement<String> createFirstUseInCommerceDate(String value) {
        return new JAXBElement<String>(_FirstUseInCommerceDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "address-5")
    public JAXBElement<String> createAddress5(String value) {
        return new JAXBElement<String>(_Address5_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "intent-to-use-in")
    public JAXBElement<String> createIntentToUseIn(String value) {
        return new JAXBElement<String>(_IntentToUseIn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "party-name")
    public JAXBElement<String> createPartyName(String value) {
        return new JAXBElement<String>(_PartyName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "code")
    public JAXBElement<String> createCode(String value) {
        return new JAXBElement<String>(_Code_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "concurrent-use-proceeding-in")
    public JAXBElement<String> createConcurrentUseProceedingIn(String value) {
        return new JAXBElement<String>(_ConcurrentUseProceedingIn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "collective-membership-mark-in")
    public JAXBElement<String> createCollectiveMembershipMarkIn(String value) {
        return new JAXBElement<String>(_CollectiveMembershipMarkIn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "law-office-assigned-location-code")
    public JAXBElement<String> createLawOfficeAssignedLocationCode(String value) {
        return new JAXBElement<String>(_LawOfficeAssignedLocationCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "attorney-name")
    public JAXBElement<String> createAttorneyName(String value) {
        return new JAXBElement<String>(_AttorneyName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "abandonment-date")
    public JAXBElement<String> createAbandonmentDate(String value) {
        return new JAXBElement<String>(_AbandonmentDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "filing-basis-filed-as-44d-in")
    public JAXBElement<String> createFilingBasisFiledAs44DIn(String value) {
        return new JAXBElement<String>(_FilingBasisFiledAs44DIn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "drawing-3d-current-in")
    public JAXBElement<String> createDrawing3DCurrentIn(String value) {
        return new JAXBElement<String>(_Drawing3DCurrentIn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "filed-as-use-application-in")
    public JAXBElement<String> createFiledAsUseApplicationIn(String value) {
        return new JAXBElement<String>(_FiledAsUseApplicationIn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "renewal-number")
    public JAXBElement<String> createRenewalNumber(String value) {
        return new JAXBElement<String>(_RenewalNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "auto-protection-date")
    public JAXBElement<String> createAutoProtectionDate(String value) {
        return new JAXBElement<String>(_AutoProtectionDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "version-no")
    public JAXBElement<String> createVersionNo(String value) {
        return new JAXBElement<String>(_VersionNo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "concurrent-use-in")
    public JAXBElement<String> createConcurrentUseIn(String value) {
        return new JAXBElement<String>(_ConcurrentUseIn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "name-change-explanation")
    public JAXBElement<String> createNameChangeExplanation(String value) {
        return new JAXBElement<String>(_NameChangeExplanation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "serial-number")
    public JAXBElement<String> createSerialNumber(String value) {
        return new JAXBElement<String>(_SerialNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "supplemental-register-amended-in")
    public JAXBElement<String> createSupplementalRegisterAmendedIn(String value) {
        return new JAXBElement<String>(_SupplementalRegisterAmendedIn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "amended-to-itu-application-in")
    public JAXBElement<String> createAmendedToItuApplicationIn(String value) {
        return new JAXBElement<String>(_AmendedToItuApplicationIn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "location-date")
    public JAXBElement<String> createLocationDate(String value) {
        return new JAXBElement<String>(_LocationDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "international-death-date")
    public JAXBElement<String> createInternationalDeathDate(String value) {
        return new JAXBElement<String>(_InternationalDeathDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "filing-basis-current-44e-in")
    public JAXBElement<String> createFilingBasisCurrent44EIn(String value) {
        return new JAXBElement<String>(_FilingBasisCurrent44EIn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "amend-to-register-date")
    public JAXBElement<String> createAmendToRegisterDate(String value) {
        return new JAXBElement<String>(_AmendToRegisterDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "filing-current-no-basis-in")
    public JAXBElement<String> createFilingCurrentNoBasisIn(String value) {
        return new JAXBElement<String>(_FilingCurrentNoBasisIn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "status-code")
    public JAXBElement<String> createStatusCode(String value) {
        return new JAXBElement<String>(_StatusCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "cancellation-pending-in")
    public JAXBElement<String> createCancellationPendingIn(String value) {
        return new JAXBElement<String>(_CancellationPendingIn_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "cancellation-code")
    public JAXBElement<String> createCancellationCode(String value) {
        return new JAXBElement<String>(_CancellationCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "registration-expiration-date")
    public JAXBElement<String> createRegistrationExpirationDate(String value) {
        return new JAXBElement<String>(_RegistrationExpirationDate_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "international-code")
    public JAXBElement<String> createInternationalCode(String value) {
        return new JAXBElement<String>(_InternationalCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "international-status-code")
    public JAXBElement<String> createInternationalStatusCode(String value) {
        return new JAXBElement<String>(_InternationalStatusCode_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "use-application-currently-in")
    public JAXBElement<String> createUseApplicationCurrentlyIn(String value) {
        return new JAXBElement<String>(_UseApplicationCurrentlyIn_QNAME, String.class, null, value);
    }

}
