//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.11 at 02:26:20 PM EEST 
//


package com.search.tm.utils.parse.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}other-related-in" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}prior-registration-application" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "otherRelatedIn",
    "priorRegistrationApplication"
})
@XmlRootElement(name = "prior-registration-applications")
public class PriorRegistrationApplications {

    @XmlElement(name = "other-related-in")
    protected List<String> otherRelatedIn;
    @XmlElement(name = "prior-registration-application")
    protected List<PriorRegistrationApplication> priorRegistrationApplication;

    /**
     * Gets the value of the otherRelatedIn property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the otherRelatedIn property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOtherRelatedIn().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getOtherRelatedIn() {
        if (otherRelatedIn == null) {
            otherRelatedIn = new ArrayList<String>();
        }
        return this.otherRelatedIn;
    }

    /**
     * Gets the value of the priorRegistrationApplication property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the priorRegistrationApplication property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPriorRegistrationApplication().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PriorRegistrationApplication }
     * 
     * 
     */
    public List<PriorRegistrationApplication> getPriorRegistrationApplication() {
        if (priorRegistrationApplication == null) {
            priorRegistrationApplication = new ArrayList<PriorRegistrationApplication>();
        }
        return this.priorRegistrationApplication;
    }

}
