//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.04.11 at 02:26:20 PM EEST 
//


package com.search.tm.utils.parse.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}version"/>
 *         &lt;element ref="{}creation-datetime"/>
 *         &lt;element ref="{}application-information"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "version",
    "creationDatetime",
    "applicationInformation"
})
@XmlRootElement(name = "trademark-applications-daily")
public class TrademarkApplicationsDaily {

    @XmlElement(required = true)
    protected Version version;
    @XmlElement(name = "creation-datetime", required = true)
    protected String creationDatetime;
    @XmlElement(name = "application-information", required = true)
    protected ApplicationInformation applicationInformation;

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link Version }
     *     
     */
    public Version getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link Version }
     *     
     */
    public void setVersion(Version value) {
        this.version = value;
    }

    /**
     * Gets the value of the creationDatetime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreationDatetime() {
        return creationDatetime;
    }

    /**
     * Sets the value of the creationDatetime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreationDatetime(String value) {
        this.creationDatetime = value;
    }

    /**
     * Gets the value of the applicationInformation property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicationInformation }
     *     
     */
    public ApplicationInformation getApplicationInformation() {
        return applicationInformation;
    }

    /**
     * Sets the value of the applicationInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicationInformation }
     *     
     */
    public void setApplicationInformation(ApplicationInformation value) {
        this.applicationInformation = value;
    }

}
